#!/usr/bin/env python3
"""Initial operator-origin audit for SFV/dSB Phase B2.

This is not a new flavor fit.  It asks whether the canonical wall basis can arise
from local scalar couplings, position-dependent but 4D-Lorentz-symmetric kinetic
normalization, and the connection generated by the rotating scalar Hessian basis.
"""
from __future__ import annotations

import json
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from chiral_localization import (  # noqa: E402
    CoordinateMap,
    WallBasis,
    build_wall_basis,
    derive_baseline_normalization,
    evaluate_route1,
    load_profile,
)

OBS = ["ct", "ut", "sb", "db", "Vus", "Vcb", "Vub"]


def dump_json(path: Path, obj: object) -> None:
    def cv(v):
        if isinstance(v, (np.floating, np.integer)):
            return v.item()
        if isinstance(v, np.ndarray):
            return v.tolist()
        if isinstance(v, dict):
            return {str(k): cv(x) for k, x in v.items()}
        if isinstance(v, (list, tuple)):
            return [cv(x) for x in v]
        return v
    path.write_text(json.dumps(cv(obj), indent=2) + "\n", encoding="utf-8")


def normalized(v: np.ndarray, mask: np.ndarray) -> tuple[np.ndarray, float]:
    s = float(np.max(np.abs(v[mask])))
    if not np.isfinite(s) or s <= 0:
        raise ValueError("Cannot normalize zero profile")
    return v / s, s


def custom_basis(base: WallBasis, O: np.ndarray, E: np.ndarray) -> WallBasis:
    return replace(base, O=O, E=E)


def observable_errors(basis: WallBasis, controls: np.ndarray, target: np.ndarray) -> np.ndarray:
    obs = evaluate_route1(basis, controls)["observables"]["values"]
    model = np.array([obs[k] for k in OBS], dtype=float)
    return 100.0 * (model / target - 1.0)


def main() -> None:
    out = ROOT / "results"
    cfg = json.loads((ROOT / "configs/coordinate_map.json").read_text())
    cmap = CoordinateMap(
        y_H=cfg["y_H"], s_H=cfg["s_H"], R_peak=cfg["R_peak"],
        w_FWHM=cfg["w_FWHM"], alpha=cfg["alpha_dr_to_dy"],
    )
    profile = load_profile(ROOT / "data/background_profile_O4_regular_robin_full.csv")
    norm = derive_baseline_normalization(profile, cmap)
    basis = build_wall_basis(profile, cmap, half_width=24.0, spacing=0.005,
                             normalization=norm)
    x = basis.x
    core = np.abs(x) <= 5.0

    # Strictly local, unsymmetrized wall functions.
    T = 1.0 - 2.0 * (basis.Phi - norm.Phi_right) / (norm.Phi_left - norm.Phi_right)
    if np.corrcoef(T[core], basis.O[core])[0, 1] < 0:
        T = -T
    G = (basis.dPhi_dy**2 + basis.dphi_dy**2) / norm.E_scale

    # Hessian angle and spatial Berry/adiabatic connection.
    h = pd.read_csv(ROOT / "data/baseline_local_hessian_and_mixing.csv")
    r = h["r"].to_numpy(float)
    two_theta = np.unwrap(np.arctan2(
        2.0 * h["H_cross"].to_numpy(float),
        h["H_PhiPhi"].to_numpy(float) - h["H_phiphi"].to_numpy(float),
    ))
    theta = 0.5 * two_theta
    R = float(profile["R_peak"].iloc[0])
    xh = cmap.alpha * (r - R)
    theta_x = np.interp(x, xh, theta, left=theta[0], right=theta[-1])
    berry = np.gradient(theta_x, x)

    candidates = {
        "minus_dPhi_dy": -basis.dPhi_dy,
        "minus_dphi_dy": -basis.dphi_dy,
        "raw_gradient_density_G": G,
        "minus_Phi_dPhi_dy": -basis.Phi * basis.dPhi_dy,
        "minus_phi_dphi_dy": -basis.phi * basis.dphi_dy,
        "minus_d_Phi_phi_dy": -(basis.phi * basis.dPhi_dy + basis.Phi * basis.dphi_dy),
        "abs_Hessian_Berry_connection": np.abs(berry),
        "signed_Hessian_Berry_connection": berry,
        "Hessian_mixing_strength": np.interp(
            x, xh, h["mixing_sin2_2theta"].to_numpy(float), left=0.0, right=0.0
        ),
    }

    rows = []
    normalized_candidates: dict[str, np.ndarray] = {}
    for name, raw in candidates.items():
        v, scale = normalized(raw, core)
        normalized_candidates[name] = v
        rows.append({
            "candidate": name,
            "normalization_max_abs_core": scale,
            "correlation_with_E": float(np.corrcoef(v[core], basis.E[core])[0, 1]),
            "correlation_with_raw_G": float(np.corrcoef(v[core], G[core])[0, 1]),
            "correlation_with_O": float(np.corrcoef(v[core], basis.O[core])[0, 1]),
            "rms_difference_from_E": float(np.sqrt(np.mean((v[core] - basis.E[core])**2))),
        })
    pd.DataFrame(rows).sort_values("correlation_with_E", ascending=False).to_csv(
        out / "operator_profile_correlations.csv", index=False
    )

    # If K(y)=K0 exp[-2 eta (Phi + r_phi phi)], canonical normalization
    # contributes eta[-Phi' - r_phi phi'] to the chiral first-order equation.
    X2 = np.column_stack([-basis.dPhi_dy[core], -basis.dphi_dy[core]])
    coeff = np.linalg.lstsq(X2, basis.E[core], rcond=None)[0]
    Ekin_raw = coeff[0] * (-basis.dPhi_dy) + coeff[1] * (-basis.dphi_dy)
    Ekin, Ekin_scale = normalized(Ekin_raw, core)
    Ekin_corr = float(np.corrcoef(Ekin[core], basis.E[core])[0, 1])
    Ekin_rel_rms = float(
        np.sqrt(np.mean((Ekin_raw[core] - basis.E[core])**2))
        / np.sqrt(np.mean(basis.E[core]**2))
    )

    X3 = np.column_stack([
        -basis.dPhi_dy[core], -basis.dphi_dy[core], np.abs(berry[core])
    ])
    coeff3 = np.linalg.lstsq(X3, basis.E[core], rcond=None)[0]
    hybrid_raw = (coeff3[0] * (-basis.dPhi_dy)
                  + coeff3[1] * (-basis.dphi_dy)
                  + coeff3[2] * np.abs(berry))
    hybrid, hybrid_scale = normalized(hybrid_raw, core)

    kernel = {
        "interpretation": (
            "A local exponential kinetic kernel K_A=K0 exp[-2 eta_A(Phi+r_phi phi)] "
            "produces a chiral connection proportional to -Phi'-r_phi phi' after canonical normalization."
        ),
        "least_squares_coefficients_to_canonical_E": {
            "minus_dPhi_dy": float(coeff[0]),
            "minus_dphi_dy": float(coeff[1]),
            "shape_ratio_r_phi": float(coeff[1] / coeff[0]),
        },
        "correlation_with_canonical_E_after_max_normalization": Ekin_corr,
        "relative_rms_error_before_max_normalization": Ekin_rel_rms,
        "hybrid_with_Berry_coefficients": {
            "minus_dPhi_dy": float(coeff3[0]),
            "minus_dphi_dy": float(coeff3[1]),
            "abs_theta_prime": float(coeff3[2]),
        },
        "hybrid_correlation_with_E": float(np.corrcoef(hybrid[core], basis.E[core])[0, 1]),
        "claim_boundary": "operator-shape evidence only; coefficients and flavor charges are not derived",
    }
    dump_json(out / "kinetic_kernel_projection.json", kernel)

    r_grad = float(h.loc[h["gradient_density"].idxmax(), "r"])
    r_mix = float(h.loc[h["mixing_sin2_2theta"].idxmax(), "r"])
    interval = (r >= min(r_grad, r_mix)) & (r <= max(r_grad, r_mix))
    theta_prime_r = np.gradient(theta, r)
    berry_diag = {
        "R_total_gradient_peak": r_grad,
        "R_max_Hessian_mixing": r_mix,
        "delta_R": r_mix - r_grad,
        "alpha_delta_R": cmap.alpha * (r_mix - r_grad),
        "integrated_abs_connection_between_landmarks_rad": float(
            np.trapezoid(np.abs(theta_prime_r[interval]), r[interval])
        ),
        "net_Hessian_rotation_between_landmarks_rad": float(abs(
            np.interp(r_mix, r, theta) - np.interp(r_grad, r, theta)
        )),
        "correlation_abs_theta_prime_with_E": float(np.corrcoef(
            normalized_candidates["abs_Hessian_Berry_connection"][core], basis.E[core]
        )[0, 1]),
        "phaseB_a_d1_formula_value": cmap.alpha * (r_mix - r_grad),
        "interpretation": (
            "Rotating to the local scalar-Hessian eigenbasis produces U^T d_y U=theta'(y) J, "
            "a spatial avoided-crossing connection.  The accepted a_d1 relation measures the "
            "coordinate width of this locking interval, while the integrated connection measures its rotation angle."
        ),
    }
    dump_json(out / "berry_locking_diagnostics.json", berry_diag)

    # Basis-dependence check for the frozen post-hoc Phase-B formulas.
    fc = json.loads((ROOT / "data/phaseB_formula_controls.json").read_text())["controls"]
    z = np.array([fc[k] for k in ["h_Q", "h_u0", "h_u1", "a_d0", "a_d1", "h_d0", "h_d1"]])
    tj = json.loads((ROOT / "configs/targets_MZ.json").read_text())["targets"]
    target = np.array([tj[k] for k in OBS], dtype=float)
    basis_cases = {
        "canonical_symmetrized_O_E": basis,
        "strictly_local_T_raw_G": custom_basis(basis, T, G),
        "strictly_local_T_kinetic_connection": custom_basis(basis, T, Ekin),
        "symmetrized_O_kinetic_connection": custom_basis(basis, basis.O, Ekin),
        "strictly_local_T_kinetic_plus_Berry": custom_basis(basis, T, hybrid),
    }
    b_rows = []
    for name, bb in basis_cases.items():
        err = observable_errors(bb, z, target)
        row = {
            "basis": name,
            "max_abs_percent_error": float(np.max(np.abs(err))),
            "rms_percent_error": float(np.sqrt(np.mean(err**2))),
        }
        row.update({f"error_{o}_pct": float(e) for o, e in zip(OBS, err)})
        b_rows.append(row)
    pd.DataFrame(b_rows).to_csv(out / "frozen_formula_basis_dependence.csv", index=False)

    summary = {
        "version": "0.1.0",
        "status": "initial operator-origin audit",
        "main_positive_results": {
            "local_kinetic_connection_correlation_with_E": Ekin_corr,
            "Hessian_Berry_connection_correlation_with_E": berry_diag[
                "correlation_abs_theta_prime_with_E"
            ],
            "locking_interval_alpha_delta_R": berry_diag["alpha_delta_R"],
            "locking_interval_rotation_angle_rad": berry_diag[
                "integrated_abs_connection_between_landmarks_rad"
            ],
        },
        "main_negative_result": (
            "The frozen seven numerical formulas are strongly basis-dependent and therefore "
            "cannot themselves be fundamental Wilson coefficients.  The local operator and "
            "canonical normalization must be derived first; effective controls are then outputs."
        ),
        "recommended_operator_ansatz": (
            "4D-Lorentz-symmetric position-dependent kinetic kernel plus a local kink mass "
            "and the Hessian-basis connection; generation dependence enters through a small, "
            "separately specified flavor generator/spurion sector."
        ),
    }
    dump_json(out / "initial_audit_summary.json", summary)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
